export const supStorageURL = "https://jwylvnqdlbtbmxsencfu.supabase.co";

export const supStorageKEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3eWx2bnFkbGJ0Ym14c2VuY2Z1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3Nzc1OTg5NSwiZXhwIjoxOTkzMzM1ODk1fQ.bYZxQ-4ElC3_PPNAbUIJV3VPpCCX9RQmpbx71O_JFrk";
